package cn.edu.sdu.software.engine

import cn.edu.sdu.software.service.ActionMappingService

class XmlAstVisitor(
    private val mappingService: ActionMappingService? = null
) : AstVisitor {

    private val sb = StringBuilder()

    // XML 文件头
    private val xmlHeader = """
        <?xml version="1.0" encoding="utf-8"?>
        <testsuite name="UiAutomatorTestSuite" tests="1" failures="0" errors="0" time="0.0">
            <testcase name="AutoGeneratedTest" classname="cn.edu.sdu.software.AutoTest">
    """.trimIndent()

    // XML 文件尾
    private val xmlFooter = """
            </testcase>
        </testsuite>
    """.trimIndent()

    init {
        sb.append(xmlHeader)
        sb.append("\n")
    }

    override fun visit(node: SequenceAstNode) {
        node.children.forEach { child ->
            child.accept(this)
        }
        sb.append(xmlFooter)
    }

    override fun visit(node: ActionAstNode) {
        val extendedMapping = mappingService?.getMapping(node.type, "XML")
        
        val codeLine = if (!extendedMapping.isNullOrBlank()) {
            buildFromTemplate(extendedMapping, node.properties)
        } else {
            getBuiltInActionCode(node)
        }
        
        sb.append("                $codeLine\n")
    }

    private fun getBuiltInActionCode(node: ActionAstNode): String {
        val props = node.properties
        return when (node.type) {
            "click" -> {
                val targetType = props["targetType"] as? String
                val elementId = props["elementId"] as? String
                if (targetType == "元素 ID" && !elementId.isNullOrEmpty()) {
                    """<action type="click" resourceId="$elementId" />"""
                } else {
                    val x = props["x"] ?: 0
                    val y = props["y"] ?: 0
                    """<action type="click" bounds="[$x,$y]" />"""
                }
            }
            "longPress" -> {
                val targetType = props["targetType"] as? String
                val elementId = props["elementId"] as? String
                val duration = props["duration"] ?: 1000
                if (targetType == "元素 ID" && !elementId.isNullOrEmpty()) {
                    """<action type="longClick" resourceId="$elementId" duration="$duration" />"""
                } else {
                    val x = props["x"] ?: 0
                    val y = props["y"] ?: 0
                    """<action type="longClick" bounds="[$x,$y]" duration="$duration" />"""
                }
            }
            "swipe" -> {
                val sx = props["startX"] ?: 0
                val sy = props["startY"] ?: 0
                val ex = props["endX"] ?: 100
                val ey = props["endY"] ?: 100
                val steps = props["steps"] ?: 50
                """<action type="swipe" startX="$sx" startY="$sy" endX="$ex" endY="$ey" steps="$steps" />"""
            }
            "input" -> {
                val text = props["text"] as? String ?: ""
                val elementId = props["elementId"] as? String
                if (!elementId.isNullOrEmpty()) {
                    """<action type="setText" resourceId="$elementId" text="$text" />"""
                } else {
                    """<!-- Error: Input operation missing elementId -->"""
                }
            }
            "wait" -> {
                val duration = props["duration"] ?: 1000
                """<action type="delay" time="$duration" />"""
            }
            "openApp" -> {
                val pkg = props["packageName"] as? String ?: ""
                """<action type="appStart" pkg="$pkg" />"""
            }
            "closeApp" -> {
                val pkg = props["packageName"] as? String ?: ""
                """<action type="appStop" pkg="$pkg" />"""
            }
            else -> """<!-- Unknown node type: ${node.type} -->"""
        }
    }

    private fun buildFromTemplate(template: String, props: Map<String, Any>): String {
        var str = template
        props.forEach { (key, value) ->
            str = str.replace("${'$'}{$key}", value.toString())
        }
        return str
    }

    fun getResult(): String {
        return sb.toString()
    }
}
